export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  HOME: '/home',
  ABOUT: '/about',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  ADMIN: '/admin',
  PRODUCT_CREATE: '/products/create',
  PRODUCT_LOGS: '/products/logs',
  PRODUCT_EDIT: '/products/:id/edit',
  PRODUCT_DETAIL: '/products/:id',
  PRODUCTS: '/products',
  CHANGE_PASSWORD: '/change-password',
  WAREHOUSE_IMPORT_RECEIPTS: '/warehouse/receipts',
  WAREHOUSE_IMPORT_RECEIPT_CREATE: '/warehouse/receipts/create',
  WAREHOUSE_IMPORT_RECEIPT_EDIT: '/warehouse/receipts/:id/edit',
  WAREHOUSE_IMPORT_RECEIPT_DETAIL: '/warehouse/receipts/:id',
};
