export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  HOME: '/home',
  ABOUT: '/about',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  ADMIN: '/admin',
  CHANGE_PASSWORD: '/change-password',
  PRODUCT_CREATE: '/products/create',
  PRODUCT_EDIT: '/products/:id/edit',
  PRODUCT_DETAIL: '/products/:id',
  PRODUCTS: '/products',
  CHANGE_PASSWORD: '/change-password',
  WAREHOUSE_IMPORT_RECEIPTS: '/warehouse/receipts',
  WAREHOUSE_IMPORT_RECEIPT_CREATE: '/warehouse/receipts/create',
  WAREHOUSE_IMPORT_RECEIPT_EDIT: '/warehouse/receipts/:id/edit',
  WAREHOUSE_IMPORT_RECEIPT_DETAIL: '/warehouse/receipts/:id',
  // Inventory
  INVENTORY: '/inventory',
  INVENTORY_DETAIL: '/inventory/detail/:id',
  INVENTORY_RECEIPT: '/inventory/receipt',
  INVENTORY_ISSUE: '/inventory/issue',
  STOCK_TRANSFER: '/inventory/transfer',
  STOCKTAKE: '/inventory/stocktake',
};
