server:
  port: 8080

spring:
  application:
    name: OSMS
  datasource:
    url: jdbc:postgresql://localhost:5432/OSMS
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  # Cấu hình SMTP Server cho Gmail (Đã chuyển về đúng nhóm spring)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000

app:
  security:
    max-failed-attempts: 5
    lock-time-duration: 5