server:
  port: 8080
spring:
  application:
    name: OSMS
  datasource:
    url: jdbc:postgresql://localhost:5432/OSMS
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_GMAIL}
    password: ${APP_PASSWORD_GMAIL}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: INFO

app:
  jwt:
    secret: ${JWT_SECRET}
    # 1 hour
    # 7 days
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:5173}

